"""Helpers for choosing archive candidates across tables."""

from __future__ import annotations

import re
from dataclasses import dataclass

from .analyzer import analyze
from .database import Database
from .inspector import describe_table, list_tables
from .models import TableInfo

# Tables the app itself generates carry recognizable name suffixes:
#   - restorer.py's temp-table mode creates "<table>_restore_<8 hex chars>"
#   - the "<table>_archive" convention is reserved for a mirrored archive table
# Both must be permanently excluded from candidacy. Otherwise a restored temp
# table (which mirrors the source schema, timestamp column included) would be
# picked up as a brand-new archive candidate on the very next run, and the app
# would start feeding its own restore output back into itself.
_RESTORE_TABLE_RE = re.compile(r"_restore_[0-9a-fA-F]{6,}$")
_ARCHIVE_TABLE_RE = re.compile(r"_archive$", re.IGNORECASE)


def _is_generated_table(name: str) -> bool:
    bare = name.split(".")[-1]
    return bool(_RESTORE_TABLE_RE.search(bare) or _ARCHIVE_TABLE_RE.search(bare))


@dataclass(frozen=True)
class ArchiveCandidate:
    name: str
    archive_column: str | None
    status: str
    reason: str


def analyze_tables(tables: list[TableInfo]) -> list[ArchiveCandidate]:
    """Return a simple archive suitability report for a set of tables."""
    results: list[ArchiveCandidate] = []
    for table in tables:
        if _is_generated_table(table.name):
            results.append(
                ArchiveCandidate(
                    table.name,
                    None,
                    "skipped",
                    "Generated by a previous archive/restore operation; excluded from analysis.",
                )
            )
            continue

        if not table.columns:
            results.append(ArchiveCandidate(table.name, None, "skipped", "No columns available."))
            continue

        if table.row_count == 0:
            results.append(ArchiveCandidate(table.name, None, "skipped", "Table is empty."))
            continue

        analysis = analyze(table)
        if analysis.chosen:
            results.append(
                ArchiveCandidate(
                    table.name,
                    analysis.chosen,
                    "eligible",
                    f"{analysis.explanation}",
                )
            )
        else:
            reason = analysis.explanation
            if "No reliable archive column" in reason:
                reason = "No timestamp column found for archival selection."
            results.append(
                ArchiveCandidate(
                    table.name,
                    None,
                    "skipped",
                    reason,
                )
            )
    return results


def analyze_database(db: Database) -> list[ArchiveCandidate]:
    """Scan every table in *db* and return an archive-suitability report.

    This is the single entry point both 'Analyze Database for Archival' and
    'Export and Archive Database' use to discover which tables exist, what
    each one's best timestamp column is, and which ones to skip — so the two
    features can never disagree about what is archivable.
    """
    tables = [describe_table(db, name) for name in list_tables(db)]
    return analyze_tables(tables)
